# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tidzam' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tidzam
pod 'GoogleMaps'
pod 'Charts'


  target 'tidzamTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'tidzamUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
